export const OFFICIAL_CANDIDATES_LIST = [
  {
    id: 0,
    name: "Oneza Umbadi",
    age: 56,
    cult: "White Gorilla Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "K'Tashe Khotare",
    age: 52,
    cult: "Lion Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "W'Kasse Zomvu",
    age: 67,
    cult: "Lion Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Amwea Thembunu",
    age: 72,
    cult: "White Gorilla Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Ch'Tahni Chite",
    age: 39,
    cult: "White Gorilla Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Mbosha Tabi",
    age: 31,
    cult: "Lion Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Kwantak Buzakhi",
    age: 65,
    cult: "Hyena Clan",
    votes: 0,
  },
  {
    id: 0,
    name: "Omeru Khibanda",
    age: 43,
    cult: "Panther Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Iwi Tamva",
    age: 72,
    cult: "Crocodile Cult",
    votes: 0,
  },
  {
    id: 0,
    name: "Jodi Tazediba",
    age: 38,
    cult: "White Gorilla Cult",
    votes: 0,
  },
];
